### ISSUE TITLE
java.lang.ClassNotFoundException: burp.BurpExtender - Burp 1.6.30 reports 

### ISSUE THREAD

**Issue by srmo** [DirectDefense/SuperSerial#2]
Trying to load the jar in the extender tab fails with 
`java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at burp.l7f.a(Unknown Source)
	at burp.l7f.<init>(Unknown Source)
	at burp.pvc.a(Unknown Source)
	at burp.mne.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
`
What am I missing?

**Comment by srmo** [comment]
I could load the plugin after following the steps to compile an empty BurpExtender jar and adding it to the Java Environment in Extender/Options

**Comment by DirectDefense** [comment]
It appears the initial release jar file was corrupted. The latest 0.3 jar file and the previous 0.2 jar file should both be working.
